### ISSUE TITLE
[Feature Request] highlight matched pattern in *hgs* buffer like the helm-buffers-list command

### ISSUE THREAD

**Issue by xuchunyang** [Sliim/helm-github-stars#2]

**Comment by Sliim** [comment]
It looks good in my Emacs.. do you have more info please?

**Comment by xuchunyang** [comment]
Search `emacs` in `helm-M-x` and `helm-github-stars`
![screen shot 2015-03-11 at 11 59 08 am](https://cloud.githubusercontent.com/assets/4550353/6590118/6d4a9c8a-c7e6-11e4-99a4-509909a5fbbc.png)
![screen shot 2015-03-11 at 11 59 25 am](https://cloud.githubusercontent.com/assets/4550353/6590119/7319291a-c7e6-11e4-8ce6-6d8ff9e71dcc.png)

**Comment by xuchunyang** [comment]
@Sliim are you sure you can get matched pattern highlighted in `*hgs` buffer? if so, I guess something might be wrong with my Helm. I just installed the latest helm from MELPA and didn't customize anything except setting some key bindings.

**Comment by Sliim** [comment]
Hmm ok, yes it works with my current setup, I will try to upgrade helm package to reproduce this issue..
