### ISSUE TITLE
Open in a new tab, not a new windows

### ISSUE THREAD

**Issue by tshu-w** [Sliim/helm-github-stars#22]
There is usually a browser window opened, so I want to open my star in a new tab, but not a new windows.

    System: macOS 10.12
    GNU Emacs 25.2.1 (x86_64-apple-darwin16.5.0, Carbon Version 157 AppKit 1504.82) of 2017-04-28

**Comment by Sliim** [comment]
What's your browser? A new tab is opened with firefox..

**Comment by tshu-w** [comment]
It's so strange, I change my default browser to chrome, a new tab is opened. Now I change back to safari, it works fine too.
Since I cannot reproduce this issue, I close it.
